# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_auto_20170518_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='New', max_length=20),
        ),
    ]
